version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rnd-server-prod
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
    env_file:
      - .env.prod
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'node', '-e', "require('http').get('http://localhost:5000/api/v1', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
