apiVersion: apps/v1
kind: Deployment
metadata:
  name: rnd-server-deployment
  labels:
    app: rnd-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rnd-server
  template:
    metadata:
      labels:
        app: rnd-server
    spec:
      containers:
      - name: rnd-server
        image: annurdev/kub-nest-app:latest
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /api/v1
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
