apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
  namespace: default
  labels:
    app: nestjs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
        - name: nestjs-app
          image: annurdev/kub-dep-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: nestjs-config
            - secretRef:
                name: nestjs-secret
