apiVersion: apps/v1
kind: Deployment
metadata:
  name: rnd-server
  namespace: rnd-server
  labels:
    app: rnd-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rnd-server
  template:
    metadata:
      labels:
        app: rnd-server
    spec:
      containers:
        - name: rnd-server
          image: annurdev/kub-nest-app:latest
          ports:
            - containerPort: 5000
              name: http
          envFrom:
            - configMapRef:
                name: rnd-server-config
            - secretRef:
                name: rnd-server-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/v1
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
