apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nestjs-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: nest.local
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: nestjs-service
                port:
                  number: 5000
          - path: /graphql(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: nestjs-service
                port:
                  number: 5000