apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
spec:
  type: LoadBalancer
  selector:
    app: nestjs-app
  ports:
    - name: http
      port: 5000        # public port
      targetPort: 5000  # container port
      nodePort: 30050   # stable NodePort (30000–32767)
      protocol: TCP
