
apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
  namespace: default
spec:
  selector:
    app: nestjs-app
  ports:
    - protocol: TCP
      port: 5000       # Service port exposed to other pods or external clients
      targetPort: 5000 # Pod container port
  type: LoadBalancer
